--[[
BACK! after 2 years


 _____                       _    ___      _           _       
/  ___|                     | |  / _ \    | |         (_)      
\ `--.__      _____  _ __ __| | / /_\ \ __| |_ __ ___  _ _ __  
 `--. \ \ /\ / / _ \| '__/ _` | |  _  |/ _` | '_ ` _ \| | '_ \ 
/\__/ /\ V  V / (_) | | | (_| | | | | | (_| | | | | | | | | | |
\____/  \_/\_/ \___/|_|  \__,_| \_| |_/\__,_|_| |_| |_|_|_| |_|
												   for everyone
                                                      version 8
                                                      
Created by "aisleofplenty" since April 2026/January 2019.

Sword Admin v8 includes:
-> 50+ commands
-> UI improvements
-> Optimizations                       

##############################################################
 _    _                  _                 
| |  | |                (_)                
| |  | | __ _ _ __ _ __  _ _ __   __ _ ___ 
| |/\| |/ _` | '__| '_ \| | '_ \ / _` / __|
\  /\  / (_| | |  | | | | | | | | (_| \__ \
 \/  \/ \__,_|_|  |_| |_|_|_| |_|\__, |___/
                                  __/ |    
                                 |___/     

Power user:
YOU UNDERSTAND THAT EDITING THIS "ADMIN COMMANDS" WITH ADJUSTED 
"POWER USER" SETTINGS ADJUSTED THROUGH THE "POWERUSERSETTINGS"
LUA SCRIPT MAKES YOUR VERSION OF SWORD ADMIN NOT REFLECT SWORD
ADMIN AS A WHOLE.

##############################################################
 _____              _ _ _       
/  __ \            | (_) |      
| /  \/_ __ ___  __| |_| |_ ___ 
| |   | '__/ _ \/ _` | | __/ __|
| \__/\ | |  __/ (_| | | |_\__ \
 \____/_|  \___|\__,_|_|\__|___/
                                
Widesteal321 - Sword Admin
F3X/GigsD4X - "Building Tools by F3X",
               public asset bundled with this

###############################################################                                                     
 _____                        _       _     _   
/  __ \                      (_)     | |   | |  
| /  \/ ___  _ __  _   _ _ __ _  __ _| |__ | |_ 
| |    / _ \| '_ \| | | | '__| |/ _` | '_ \| __|
| \__/\ (_) | |_) | |_| | |  | | (_| | | | | |_ 
 \____/\___/| .__/ \__, |_|  |_|\__, |_| |_|\__|
            | |     __/ |        __/ |          
            |_|    |___/        |___/ 
            
Copyright (c) 2026 Sword Admin

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
]]